# fly.toml file generated for tt-site on 2022-11-19T00:24:23-08:00

app = "tt-site"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "yarn prisma migrate deploy"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
