# fly.toml file generated for tt-postgres on 2022-11-05T22:48:35-07:00

app = "tt-postgres"
kill_signal = "SIGINT"
kill_timeout = 30

[deploy]
  strategy = "rolling"

[env]
  PGDATA = "/var/lib/postgresql/data/pgdata"

[mounts]
  destination = "/var/lib/postgresql/data"
  source = "main"

[[services]]
  internal_port = "5432"
  protocol = "tcp"

  [[services.ports]]
    port = "5432"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "30s"
    restart_limit = 0
    timeout = "5s"
