# fly.toml file generated for tt-redis on 2022-11-05T22:05:03-07:00

app = "tt-redis"
kill_signal = "SIGINT"
kill_timeout = 30

[deploy]
  strategy = "rolling"

[[services]]
  internal_port = "6379"
  protocol = "tcp"

  [[services.ports]]
    port = "6379"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "30s"
    restart_limit = 0
    timeout = "5s"
